#!/bin/sh
#
# Copyright (C) 2013-2014 OpenMediaVault Plugin Developers
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

PHP_FPM_POOL_DIR=/etc/php5/fpm/pool.d

VIRTUALBOX_POOL_CONF="${PHP_FPM_POOL_DIR}/openmediavault-virtualbox.conf"

if [ -e "${VIRTUALBOX_POOL_CONF}" ]; then
    rm ${VIRTUALBOX_POOL_CONF}
fi

if [ "$(omv_config_get "//services/virtualbox/enable")" != "1" ]; then
    exit 0
fi

cat <<EOF > "${VIRTUALBOX_POOL_CONF}"
[openmediavault-virtualbox]
listen = /var/run/php5-fpm-openmediavault-virtualbox.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0600

user = openmediavault
group = openmediavault

pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; php.ini settings
php_value[include_path] = ".:/usr/share/php:/usr/share/phpvirtualbox"
php_value[post_max_size] = 25M
php_value[upload_max_filesize] = 25M
php_value[expose_php] = Off
php_value[session.name] = VIRTUALBOXSESSID

EOF

exit 0
