#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

VIRTUALBOX_SITE_CONF="/etc/nginx/openmediavault-webgui.d/openmediavault-virtualbox.conf"
VIRTUALBOX_POOL_CONF="/etc/php5/fpm/pool.d/openmediavault-virtualbox.conf"

case "$1" in
    purge)
        omv_config_delete "/config/services/virtualbox"
    ;;

    remove)
        if [ -e "${VIRTUALBOX_SITE_CONF}" ]; then
            rm ${VIRTUALBOX_SITE_CONF}
        fi

        if [ -e "${VIRTUALBOX_POOL_CONF}" ]; then
            rm ${VIRTUALBOX_POOL_CONF}
        fi

        systemctl reload nginx.service
        systemctl reload php5-fpm.service
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
