#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

DEFAULT_FILE="/etc/default/openmediavault-virtualbox"
OMV_VBOX_USER="vbox"

create_vbox_user()
{
    # Generate password
    # TODO: use stronger hash? Only md5 seems to be available
    # with makepasswd
    NPSWD=$(makepasswd --crypt-md5 --chars=10)
    NPSWD_CLEAR=$(echo ${NPSWD} | awk '{ print $1 }')
    NPSWD_CRYPT=$(echo ${NPSWD} | awk '{ print $2 }')

    # Create the user
    useradd -d /home/${OMV_VBOX_USER} -c "openmediavault-virtualbox" -m -p ${NPSWD_CRYPT} -N -g vboxusers ${OMV_VBOX_USER}

    # Store the password for later use
    echo "${NPSWD_CLEAR}" > ${DEFAULT_FILE}
}

case "$1" in
    configure)
        SERVICE_XPATH_NAME="virtualbox"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        # Add the default configuration
        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "enable_advanced" "0"
            omv_config_add_element "${SERVICE_XPATH}" "vm_folder"
            omv_config_add_element "${SERVICE_XPATH}" "show_tab" "0"
        fi

        # Generate the package default file
        if [ ! -e ${DEFAULT_FILE} ]; then
            if ! getent passwd ${OMV_VBOX_USER}; then
                create_vbox_user
            fi
        fi

        # Set the correct permissions on files
        chown openmediavault:openmediavault ${DEFAULT_FILE}
        chmod 0600 ${DEFAULT_FILE}

        # Manage vboxinit (origin: phpvirtualbox)
        if [ -x "/etc/init.d/vboxinit" ]; then
            update-rc.d vboxinit defaults

            if [ "$(omv_config_get "//services/virtualbox/enable")" != "1" ]; then
                update-rc.d vboxinit disable
            fi
        fi

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
