#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

VIRTUALBOX_SITE_CONF="/etc/nginx/openmediavault-webgui.d/openmediavault-virtualbox.conf"

case "$1" in
    purge)
        omv_config_delete "//services/virtualbox"
    ;;
    remove)
        omv_config_delete "//services/virtualbox"

        if [ -e "${VIRTUALBOX_SITE_CONF}" ]; then
            rm ${VIRTUALBOX_SITE_CONF}
        fi

        service nginx reload
    ;;
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
