#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_VIRTUALBOX_DEFAULT_CONF="/etc/default/openmediavault-virtualbox"
OMV_VIRTUALBOX_USER="vbox"
OMV_VIRTUALBOX_USER_HOME="/var/lib/vbox"

data_drive_to_shared_folder()
{
    name="VirtualBoxMachines"
    comment="VirtualBox machines location"
    mntentref=$(omv_config_get "//services/virtualbox/mntentref")
    reldirpath="virtualbox-machines"

    if [ -z "${mntentref}" ]; then
        omv_config_add_element "/config/virtualbox/mysql" "machines.sharedfolderref"

        return 0
    fi

    # Prepare JSON data.
    json="{ \"uuid\": \"undefined\", \"name\": \"${name}\", \"comment\": \"${comment}\", \"mntentref\": \"${mntentref}\", \"reldirpath\": \"${reldirpath}\" }"

    # Call omv-rcp and create the shared folder and then filter out the
    # uuid of the new shared folder.
    uuid=$(omv-rpc ShareMgmt set "${json}" | grep -Po '(?<="uuid":")[^"]*')

    # Add the shared folder to the plugin config.
    omv_config_add_element "/config/services/virtualbox" "machines.sharedfolderref" $uuid
}

create_vbox_user()
{
    # Generate the password.
    # TODO: use stronger hash? Only md5 seems to be available
    # with makepasswd.
    NPSWD=$(makepasswd --crypt-md5 --chars=10)
    NPSWD_CLEAR=$(echo ${NPSWD} | awk '{ print $1 }')
    NPSWD_CRYPT=$(echo ${NPSWD} | awk '{ print $2 }')

    # Create the user.
    useradd --system \
            --create-home \
            --home-dir ${OMV_VIRTUALBOX_USER_HOME} \
            --no-user-group \
            --gid vboxusers \
            --password ${NPSWD_CRYPT} \
            ${OMV_VIRTUALBOX_USER}

    # Store the password for later use.
    echo "${NPSWD_CLEAR}" > ${OMV_VIRTUALBOX_DEFAULT_CONF}
}

case "$1" in
    configure)
        SERVICE_XPATH_NAME="virtualbox"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        # Add the default configuration.
        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "enable_advanced" "0"
            omv_config_add_element "${SERVICE_XPATH}" "machines.sharedfolderref"
            omv_config_add_element "${SERVICE_XPATH}" "show_tab" "0"
        fi

        # Generate the package default file.
        if [ ! -e ${OMV_VIRTUALBOX_DEFAULT_CONF} ]; then
            if ! getent passwd ${OMV_VIRTUALBOX_USER}; then
                create_vbox_user
            fi
        fi

        # add vbox user to cdrom group
        if ! id -nG "${OMV_VIRTUALBOX_USER}" | grep -qw "cdrom"; then
            usermod -a -G cdrom ${OMV_VIRTUALBOX_USER}
        fi

        # Set the correct permissions on files.
        chown openmediavault:openmediavault ${OMV_VIRTUALBOX_DEFAULT_CONF}
        chmod 0600 ${OMV_VIRTUALBOX_DEFAULT_CONF}

        # Manage vboxinit (origin: phpvirtualbox).
        if [ -x "/etc/init.d/vboxinit" ]; then
            update-rc.d vboxinit defaults

            if [ "$(omv_config_get "//services/virtualbox/enable")" != "1" ]; then
                update-rc.d vboxinit disable
            fi
        fi

        if dpkg --compare-versions "$2" lt-nl "1.0.11"; then
            data_drive_to_shared_folder
        fi

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
